from . import controllers_norton_assessment
from . import controllers_scalefrail_assessment
from . import controllers_scalefrail_question
from . import controllers_scalefrail_answer
from . import controllers_scalegds5_answer
from . import controllers_scalegds5_assessment
from . import controllers_scalegds5_question
from . import controllers_scalesarcf_question
from . import controllers_scalesarcf_answer
from . import controllers_scalesarcf_assessment
from . import controllers_barthel_question
from . import controllers_barthel_answer
from . import controllers_barthel_assessment
from . import controllers_lawton_brody_answer
from . import controllers_lawton_brody_question
from . import controllers_lawton_brody_assessment
